services:
  app:
    env_file: .docker.env
    restart: 'unless-stopped'
    build:
      context: ./docker/
      dockerfile: dev.Dockerfile
    links:
      - db:db
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ~:/home/sail
    depends_on:
      - "db"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=boopbot.app"
  db:
    env_file: .docker.env
    image: postgres:14
    restart: 'unless-stopped'
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ${PWD}/docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "65433:5432"
  queue:
    env_file: .docker.env
    restart: 'unless-stopped'
    build:
      context: ./docker/
      dockerfile: dev.Dockerfile
    links:
      - db:db
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - "db"
    command: "/bin/sh -c 'php artisan queue:work --delay=10 --memory=2048 --timeout=3600 --max-jobs=10'"
  nginx:
    image: nginx:stable
    restart: 'unless-stopped'
    working_dir: /var/www
    depends_on:
      - "app"
    ports:
      - "8532:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
